# Generated by Django 2.2.12 on 2021-06-03 07:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_of_correct_answers',
        ),
        migrations.AddField(
            model_name='player',
            name='num_of_correct_answers_part1',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
