# Generated by Django 2.2.12 on 2021-06-03 21:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0002_auto_20210603_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='self_evaluation1',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
