# Generated by Django 2.2.12 on 2021-06-03 22:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0003_player_self_evaluation1'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatment_group',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
