# Generated by Django 2.2.12 on 2021-06-03 22:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0004_player_treatment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='self_evaluation2',
            field=otree.db.models.FloatField(choices=[[0.1, '10%'], [0.2, '20%'], [0.3, '30%'], [0.4, '40%'], [0.5, '50%'], [0.6, '60%'], [0.7, '70%'], [0.8, '80%'], [0.9, '90%'], [1, '100%']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='self_evaluation1',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
