# Generated by Django 2.2.12 on 2021-06-03 22:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0005_auto_20210603_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_evaluation2',
            field=otree.db.models.IntegerField(choices=[[10, '10%'], [20, '20%'], [30, '30%'], [40, '40%'], [50, '50%'], [60, '60%'], [70, '70%'], [80, '80%'], [90, '90%'], [100, '100%']], null=True),
        ),
    ]
