# Generated by Django 2.2.12 on 2021-06-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part1', '0007_auto_20210603_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='treatment_group',
        ),
    ]
