# Generated by Django 2.2.12 on 2021-06-09 07:39

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'demographics_survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographics_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'demographics_survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('ethnicity', otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='1. Are you of Hispanic, Latino, or Spanish origin?')),
                ('race', otree.db.models.IntegerField(choices=[[0, 'American Indian or Alaska Native'], [1, 'Asian'], [2, 'Black or African American'], [3, 'Native Hawaiian or Other Pacific Islander'], [4, 'White or Caucasian'], [5, 'Middle Eastern'], [6, 'Hispanic, Latino, or Spanish'], [7, 'Other']], null=True, verbose_name='2. How would you best describe yourself?')),
                ('education', otree.db.models.IntegerField(choices=[[1, 'Freshman'], [2, 'Sophomore'], [3, 'Junior'], [4, 'Senior'], [5, 'Graduate (Master Degree)'], [6, 'Graduate (Doctoral Degree)']], null=True, verbose_name='3. What year are you in UCSC?')),
                ('major', otree.db.models.StringField(max_length=10000, null=True, verbose_name='4. What is your major?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_survey.Subsession')),
            ],
            options={
                'db_table': 'demographics_survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_survey.Subsession'),
        ),
    ]
