# Generated by Django 2.2.12 on 2021-05-13 05:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.IntegerField(null=True, verbose_name='1. How old are you?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.IntegerField(choices=[[1, 'Freshman'], [2, 'Sophomore'], [3, 'Junior'], [4, 'Senior'], [5, 'Graduate (Master Degree)'], [6, 'Graduate (Doctoral Degree)']], null=True, verbose_name='5. What year are you in UCSC?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ethnicity',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='3. Are you of Hispanic, Latino, or Spanish origin?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.IntegerField(choices=[[0, 'Male'], [1, 'Female'], [2, 'Other'], [3, 'Prefer not to say']], null=True, verbose_name='2. What is your gender?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='major',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='6. What is your major?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=otree.db.models.IntegerField(choices=[[0, 'American Indian or Alaska Native'], [1, 'Asian'], [2, 'Black or African American'], [3, 'Native Hawaiian or Other Pacific Islander'], [4, 'White or Caucasian'], [5, 'Middle Eastern'], [6, 'Hispanic, Latino, or Spanish'], [7, 'Other']], null=True, verbose_name='4. How would you best describe yourself?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_ID',
            field=otree.db.models.IntegerField(null=True, verbose_name='7. What is your UCSC student ID?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='venmo',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='8. What is your Venmo?'),
        ),
    ]
