# Generated by Django 2.2.12 on 2021-05-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics_survey', '0002_auto_20210512_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='student_ID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='venmo',
        ),
    ]
