# Generated by Django 2.2.12 on 2021-05-19 06:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics_survey', '0003_auto_20210516_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.AlterField(
            model_name='player',
            name='education',
            field=otree.db.models.IntegerField(choices=[[1, 'Freshman'], [2, 'Sophomore'], [3, 'Junior'], [4, 'Senior'], [5, 'Graduate (Master Degree)'], [6, 'Graduate (Doctoral Degree)']], null=True, verbose_name='3. What year are you in UCSC?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ethnicity',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='1. Are you of Hispanic, Latino, or Spanish origin?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='major',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='4. What is your major?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=otree.db.models.IntegerField(choices=[[0, 'American Indian or Alaska Native'], [1, 'Asian'], [2, 'Black or African American'], [3, 'Native Hawaiian or Other Pacific Islander'], [4, 'White or Caucasian'], [5, 'Middle Eastern'], [6, 'Hispanic, Latino, or Spanish'], [7, 'Other']], null=True, verbose_name='2. How would you best describe yourself?'),
        ),
    ]
