# Generated by Django 2.2.12 on 2021-06-03 23:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0011_auto_20210603_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Corporate Bonds'], [2, 'B. Stocks'], [3, 'C. U.S Treasury Bond'], [4, 'D. Mutual Funds']], null=True, verbose_name='\n        What is a stock dividend? \n            '),
        ),
    ]
