# Generated by Django 2.2.12 on 2021-06-03 23:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0014_auto_20210603_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. The price the stock is sold for'], [2, 'B. Part of a company’s profit that is paid to owners'], [3, 'C. A capital gain'], [4, 'D. Mutual Funds']], null=True, verbose_name='\n        What is a stock dividend? \n            '),
        ),
    ]
