# Generated by Django 2.2.12 on 2021-06-03 23:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0016_auto_20210603_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_skill_question4',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n        Why would someone buy a bond instead of a stock?\n                        '),
        ),
    ]
