# Generated by Django 2.2.12 on 2021-06-03 23:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0022_auto_20210603_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_skill_question5',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Rise'], [2, 'B. Fall'], [3, 'C. Stay the Same'], [4, 'D. No Relationship']], null=True, verbose_name='\n        The following graph shows the price of one Rich Rock share over a 12-month period.\n        Which of the following statements is true?\n                        '),
        ),
    ]
