# Generated by Django 2.2.12 on 2021-06-03 23:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0026_auto_20210603_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_skill_question5',
            field=otree.db.models.IntegerField(choices=[[1, 'A. The best month to buy the shares was February or March'], [2, 'B. The share price increased by about 50% over the year'], [3, 'C. The best month to buy the shares was September'], [4, 'D. None of the above']], null=True, verbose_name='\n        The following graph shows the price of one Rich Rock share over a 12-month period.\n        Which of the following statements is true?\n                        '),
        ),
    ]
