# Generated by Django 2.2.12 on 2021-06-04 02:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task_part2', '0028_auto_20210603_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='part2_confidence_level_question1',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How confident are you about your answer? (1 = not confident at all; 7 = completely confident)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='part2_confidence_level_question2',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How confident are you about your answer? (1 = not confident at all; 7 = completely confident)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='part2_confidence_level_question3',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How confident are you about your answer? (1 = not confident at all; 7 = completely confident)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='part2_confidence_level_question4',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How confident are you about your answer? (1 = not confident at all; 7 = completely confident)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='part2_confidence_level_question5',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How confident are you about your answer? (1 = not confident at all; 7 = completely confident)'),
        ),
    ]
