# Generated by Django 2.2.12 on 2021-06-03 06:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dna_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='female_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='male_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='other_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
