# Generated by Django 2.2.12 on 2021-06-09 07:39

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_game_part2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Investment_game_part2_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_game_part2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Investment_game_part2_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('game2_slider1', otree.db.models.FloatField(null=True)),
                ('game2_slider2', otree.db.models.FloatField(null=True)),
                ('game2_slider3', otree.db.models.FloatField(null=True)),
                ('game2_slider4', otree.db.models.FloatField(null=True)),
                ('game2_slider5', otree.db.models.FloatField(null=True)),
                ('game2_slider6', otree.db.models.FloatField(null=True)),
                ('game2_slider7', otree.db.models.FloatField(null=True)),
                ('game2_slider8', otree.db.models.FloatField(null=True)),
                ('game2_slider9', otree.db.models.FloatField(null=True)),
                ('prob_A_1', otree.db.models.FloatField(default=0.1, null=True)),
                ('prob_A_2', otree.db.models.FloatField(default=0.2, null=True)),
                ('prob_A_3', otree.db.models.FloatField(default=0.3, null=True)),
                ('prob_A_4', otree.db.models.FloatField(default=0.4, null=True)),
                ('prob_A_5', otree.db.models.FloatField(default=0.5, null=True)),
                ('prob_A_6', otree.db.models.FloatField(default=0.6, null=True)),
                ('prob_A_7', otree.db.models.FloatField(default=0.7, null=True)),
                ('prob_A_8', otree.db.models.FloatField(default=0.8, null=True)),
                ('prob_A_9', otree.db.models.FloatField(default=0.9, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Investment_game_part2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_game_part2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_game_part2_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Investment_game_part2.Subsession')),
            ],
            options={
                'db_table': 'Investment_game_part2_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Investment_game_part2.Subsession'),
        ),
    ]
