# Generated by Django 2.2.12 on 2021-05-21 07:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='answer',
        ),
        migrations.AddField(
            model_name='player',
            name='skill_answer',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
