# Generated by Django 2.2.12 on 2021-05-22 19:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0004_auto_20210521_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confidence',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dna_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='female_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='male_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='other_count',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
