# Generated by Django 2.2.12 on 2021-05-22 19:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0005_auto_20210522_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence',
            field=otree.db.models.IntegerField(choices=[[1, 'Completely unconfident'], 2, 3, 4, 5, 6, [7, 'Completely confident']], null=True),
        ),
    ]
