# Generated by Django 2.2.12 on 2021-05-22 19:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0006_auto_20210522_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True),
        ),
    ]
