# Generated by Django 2.2.12 on 2021-05-22 20:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0007_auto_20210522_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='treatment_group',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
