# Generated by Django 2.2.12 on 2021-05-26 16:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0010_auto_20210525_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_of_correct_answers',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
