# Generated by Django 2.2.12 on 2021-05-27 03:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0011_player_num_of_correct_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_of_correct_answers',
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_1',
            field=otree.db.models.FloatField(default=0.1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_2',
            field=otree.db.models.FloatField(default=0.2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_3',
            field=otree.db.models.FloatField(default=0.3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_4',
            field=otree.db.models.FloatField(default=0.4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_5',
            field=otree.db.models.FloatField(default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_6',
            field=otree.db.models.FloatField(default=0.6, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_7',
            field=otree.db.models.FloatField(default=0.7, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_8',
            field=otree.db.models.FloatField(default=0.8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='prob_A_9',
            field=otree.db.models.FloatField(default=0.9, null=True),
        ),
    ]
