# Generated by Django 2.2.12 on 2021-05-27 05:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0012_auto_20210526_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_of_correct',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
