# Generated by Django 2.2.12 on 2021-05-27 05:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0013_player_num_of_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_of_correct',
        ),
        migrations.AddField(
            model_name='player',
            name='num_of_correct_answers',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
