# Generated by Django 2.2.12 on 2021-05-27 05:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0014_auto_20210526_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='if_skill_answer_correct',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
