# Generated by Django 2.2.12 on 2021-05-27 05:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0015_player_if_skill_answer_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='if_skill_answer_correct',
        ),
        migrations.AddField(
            model_name='player',
            name='if_skill_question_correct',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
