# Generated by Django 2.2.12 on 2021-06-02 16:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0018_auto_20210602_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_slider',
            field=otree.db.models.IntegerField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
    ]
