# Generated by Django 2.2.12 on 2021-06-02 19:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_task', '0020_auto_20210602_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='allocation_a',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allocation_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_slider',
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a1',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a2',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a3',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a4',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a5',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a6',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a7',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a8',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_a9',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b1',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b2',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b3',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b4',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b5',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b6',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b7',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b8',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='allocation_b9',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider1',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider2',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider3',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider4',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider5',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider6',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider7',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider8',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_slider9',
            field=otree.db.models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], null=True),
        ),
    ]
