# Generated by Django 2.2.12 on 2021-05-12 00:26

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tasks_group', to='otree.Session')),
            ],
            options={
                'db_table': 'skill_tasks_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_tasks_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'skill_tasks_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('confidence_level_question', otree.db.models.IntegerField(null=True, verbose_name='What is your confidence level? (out of 10)')),
                ('skill_question1', otree.db.models.IntegerField(choices=[[1, 'A. More than $102'], [2, 'B. Exactly $102'], [3, 'C. Less than $102'], [4, 'D. Don’t Know']], null=True, verbose_name='\n        Suppose you have $100 in a savings account earning 2 percent interest a year. \n        After five years, how much would you have?\n        ')),
                ('skill_question2', otree.db.models.IntegerField(choices=[[1, 'A. More'], [2, 'B. Same'], [3, 'C. Less'], [4, 'D. Don’t Know']], null=True, verbose_name='\n            Imagine that the interest rate on your savings account is 1 percent a year and inflation is 2 percent a year. \n            After one year, would the money in the account buy more than it does today, exactly the same or less than today?\n            ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_tasks.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tasks_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tasks_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_tasks.Subsession')),
            ],
            options={
                'db_table': 'skill_tasks_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_tasks.Subsession'),
        ),
    ]
