# Generated by Django 2.2.12 on 2021-05-13 18:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill_question1',
            field=otree.db.models.IntegerField(choices=[[1, 'A. More than $102'], [2, 'B. Exactly $102'], [3, 'C. Less than $102']], null=True, verbose_name='\n        Suppose you have $100 in a savings account earning 2 percent interest a year. \n        After five years, how much would you have?\n        '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question2',
            field=otree.db.models.IntegerField(choices=[[1, 'A. More'], [2, 'B. Same'], [3, 'C. Less']], null=True, verbose_name='\n            Imagine that the interest rate on your savings account is 1 percent a year and inflation is 2 percent a year. \n            After one year, would the money in the account buy more than it does today, exactly the same or less than today?\n            '),
        ),
    ]
