# Generated by Django 2.2.12 on 2021-05-13 18:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0002_auto_20210513_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. More'], [2, 'B. Same'], [3, 'C. Less']], null=True, verbose_name='\n                Imagine that the interest rate on your savings account is 1 percent a year and inflation is 2 percent a year. \n                After one year, would the money in the account buy more than it does today, exactly the same or less than today?\n                '),
        ),
    ]
