# Generated by Django 2.2.12 on 2021-05-13 18:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0003_player_skill_question3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                Buying a single company’s stock usually provides a safer return than astock mutual fund.\n            '),
        ),
    ]
