# Generated by Django 2.2.12 on 2021-05-13 18:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0004_auto_20210513_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_question4',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                    Buying a single company’s stock usually provides a safer return than astock mutual fund.\n                '),
        ),
    ]
