# Generated by Django 2.2.12 on 2021-05-13 18:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0005_player_skill_question4'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_question5',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                    A 15-year mortgage typically requires higher monthly payments than a30-year mortgage but the total \n                    interest over the life of the loan will be less.\n                '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question4',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                    A 15-year mortgage typically requires higher monthly payments than a30-year mortgage but the total \n                    interest over the life of the loan will be less.\n                '),
        ),
    ]
