# Generated by Django 2.2.12 on 2021-05-13 19:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0011_auto_20210513_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_question6',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Rise'], [2, 'B. Fall'], [3, 'C. Stay the Same'], [4, 'D. No Relationship']], null=True, verbose_name='\n                    If interest rates rise, what will typically happen to bond prices?  \n                    Rise,fall, stay the same, or is there no relationship?\n                '),
        ),
    ]
