# Generated by Django 2.2.12 on 2021-05-13 19:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0017_auto_20210513_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question',
            field=otree.db.models.IntegerField(choices=[[1, 'A. I Am Not Confident'], [2, 'B. I Am Somewhat Confident'], [3, 'C. I Am Confident'], [4, 'D. I Am Very Confident']], null=True, verbose_name='How Confident Are You about Your Answers?'),
        ),
    ]
