# Generated by Django 2.2.12 on 2021-05-13 19:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0019_auto_20210513_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confidence_overall1',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Less than 2'], [2, 'B. 2 to 3'], [3, 'C. 4 to 5'], [4, 'D. 5 or more']], null=True, verbose_name='\n                    Among all skill questions you answered, how many questions do you think you answered correctly?\n                '),
        ),
        migrations.AddField(
            model_name='player',
            name='confidence_overall2',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Top 25%'], [2, 'B. Top 50%'], [3, 'C. Bottom 50%'], [4, 'D. Bottom 25%']], null=True, verbose_name='\n                        What rankings do you think you are in the all subjects?\n                    '),
        ),
    ]
