# Generated by Django 2.2.12 on 2021-05-17 03:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0020_auto_20210513_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question1',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question2',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question3',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question4',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question5',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question6',
            field=otree.db.models.IntegerField(null=True, verbose_name='How Confident Are You about Your Answers? (out of 7)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                Buying a single company’s stock usually provides a safer return than a stock mutual fund.\n            '),
        ),
    ]
