# Generated by Django 2.2.12 on 2021-05-21 04:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_tasks', '0021_auto_20210516_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='confidence_overall1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='confidence_overall2',
        ),
        migrations.AddField(
            model_name='player',
            name='confidence_level_question10',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='confidence_level_question7',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='confidence_level_question8',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='confidence_level_question9',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question1',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question2',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question3',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question4',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question5',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='confidence_level_question6',
            field=otree.db.models.IntegerField(choices=[[1, '1 - Completely unconfident'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 - Completely confident']], null=True, verbose_name='How confident are you about your answer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question1',
            field=otree.db.models.IntegerField(choices=[[1, 'A. More than $102'], [2, 'B. Exactly $102'], [3, 'C. Less than $102']], null=True, verbose_name='\n                Suppose you have $100 in a savings account earning 2 percent interest a year. \n                After five years, how much would you have?\n                '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question2',
            field=otree.db.models.IntegerField(choices=[[1, 'A. More'], [2, 'B. Same'], [3, 'C. Less']], null=True, verbose_name='\n                    Imagine that the interest rate on your savings account is 1 percent a year and inflation is 2 percent a year. \n                    After one year, would the money in the account buy more than it does today, exactly the same or less than today?\n                    '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question3',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n                        Buying a single company’s stock usually provides a safer return than a stock mutual fund.\n                    '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question4',
            field=otree.db.models.IntegerField(choices=[[1, 'A. True'], [2, 'B. False']], null=True, verbose_name='\n        A 15-year mortgage typically requires higher monthly payments than a30-year mortgage but the total \n        interest over the life of the loan will be less.\n                        '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question5',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Rise'], [2, 'B. Fall'], [3, 'C. Stay the Same'], [4, 'D. No Relationship']], null=True, verbose_name='\n        If interest rates rise, what will typically happen to bond prices?  \n        Rise,fall, stay the same, or is there no relationship?\n                        '),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_question6',
            field=otree.db.models.IntegerField(choices=[[1, 'A. Less than 2 years'], [2, 'B. 2 to 4 years'], [3, 'C. 5 to 9 years'], [4, 'D. 10 or more years']], null=True, verbose_name='\n        Suppose you owe $1,000 on a loan and the interest rate you are charged is 20% per year compounded annually.  \n        If you didn’t pay anything off, at this interest rate, how many years would it take for the amount you owe to double?\n                        '),
        ),
    ]
